name: GitHub Actions Demo
run-name: supraj 
on: push
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest


    steps:
    - uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        add_approver_team: supraj
        minimum-approvals: 1
        issue-title: "Deploying v1.3.5 to prod from staging"
        exclude-workflow-initiator-as-approver: false
      
