name: GitHub Actions Demo
run-name: supraj 
on: push
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest


    steps:
      - uses: macnev2013/manual-approval@latest
        with:
          secret: ${{ github.TOKEN }}
          approvers: supraj,SuprajMaripeddi
          minimum-approvals: 1
          approval-wait: 600
          issue-title: 'Manual Approval'
          issue-body: |
            "Issue Body"
#     - uses: trstringer/manual-approval@v1
#       with:
#         secret: ${{ github.TOKEN }}
#         approvers: SuprajMaripeddi,DevOps-Cloud-Freelance/supraj
#         minimum-approvals: 1
#         issue-title: "Deploying v1.3.5 to prod from staging"
#         exclude-workflow-initiator-as-approver: false
      
